Document: trojita
Title: Debian trojita Manual
Author: <insert document author here>
Abstract: This manual describes what trojita is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/trojita/trojita.sgml.gz

Format: postscript
Files: /usr/share/doc/trojita/trojita.ps.gz

Format: text
Files: /usr/share/doc/trojita/trojita.text.gz

Format: HTML
Index: /usr/share/doc/trojita/html/index.html
Files: /usr/share/doc/trojita/html/*.html
